print("Chester Luke A. Maligaso")
print("Libtangin, Gasan, Marinduque")
print("August 29, 2003")
print("")
print("Marinduque State College")
print("Bachelor of Science in Information Technology")
print("BSIT - 2A")
print("")
print("Playing basketball.")
print("Watching animes and movies.")
print("learning programming.")
print("Play a guitar. and;")
print("Singing")

